In [1]:
import pandas as pd
akc = pd.read_csv('data/raw/akc-dog-breeds.csv')
akc.head()

,Unnamed: 0,description,temperament,popularity,min_height,max_height,min_weight,max_weight,min_expectancy,max_expectancy,...,grooming_frequency_value,grooming_frequency_category,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category
0,Affenpinscher,The Affen’s apish look has been described many...,"Confident, Famously Funny, Fearless",148,22.86,29.21,3.175147,4.535924,12.0,15.0,...,0.6,2-3 Times a Week Brushing,0.6,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing
1,Afghan Hound,"The Afghan Hound is an ancient breed, his whol...","Dignified, Profoundly Loyal, Aristocratic",113,63.50,68.58,22.679619,27.215542,12.0,15.0,...,0.8,Daily Brushing,0.2,Infrequent,0.8,Energetic,0.2,May be Stubborn,0.2,Aloof/Wary
2,Airedale Terrier,The Airedale Terrier is the largest of all ter...,"Friendly, Clever, Courageous",60,58.42,58.42,22.679619,31.751466,11.0,14.0,...,0.6,2-3 Times a Week Brushing,0.4,Occasional,0.6,Regular Exercise,1.0,Eager to Please,0.8,Friendly
3,Akita,"Akitas are burly, heavy-boned spitz-type dogs ...","Courageous, Dignified, Profoundly Loyal",47,60.96,71.12,31.751466,58.967008,10.0,13.0,...,0.8,Daily Brushing,0.6,Seasonal,0.8,Energetic,1.0,Eager to Please,0.6,Alert/Responsive
4,Alaskan Malamute,The Alaskan Malamute stands 23 to 25 inches at...,"Affectionate, Loyal, Playful",58,58.42,63.50,34.019428,38.555351,10.0,14.0,...,0.6,2-3 Times a Week Brushing,0.6,Seasonal,0.8,Energetic,0.4,Independent,0.8,Friendly

In [15]:
import pandas as pd
akc = pd.read_csv('data/raw/akc-dog-breeds.csv')
akc[['grooming_frequency_value','shedding_value',
            'energy_level_value','trainability_value','demeanor_value']].head(10)

,grooming_frequency_value,shedding_value,energy_level_value,trainability_value,demeanor_value
0,0.6,0.6,0.6,0.8,1.0
1,0.8,0.2,0.8,0.2,0.2
2,0.6,0.4,0.6,1.0,0.8
3,0.8,0.6,0.8,1.0,0.6
4,0.6,0.6,0.8,0.4,0.8
5,0.2,0.6,0.8,0.6,0.6
6,0.2,0.4,0.8,0.6,0.6
7,0.4,0.6,0.8,1.0,1.0
8,0.2,0.6,0.8,0.4,0.8
9,NaN,NaN,NaN,NaN,NaN

In [16]:
import pandas as pd
akc = pd.read_csv('data/raw/akc-dog-breeds.csv')
akc['temperament'].head(5)

0          Confident, Famously Funny, Fearless
1    Dignified, Profoundly Loyal, Aristocratic
2                 Friendly, Clever, Courageous
3      Courageous, Dignified, Profoundly Loyal
4                 Affectionate, Loyal, Playful
Name: temperament, dtype: str

In [17]:
import pandas as pd
akc = pd.read_csv('data/raw/akc-dog-breeds.csv')
akc['description'].head(5)

0    The Affen’s apish look has been described many...
1    The Afghan Hound is an ancient breed, his whol...
2    The Airedale Terrier is the largest of all ter...
3    Akitas are burly, heavy-boned spitz-type dogs ...
4    The Alaskan Malamute stands 23 to 25 inches at...
Name: description, dtype: str

In [18]:
import pandas as pd
akc = pd.read_csv('data/raw/akc-dog-breeds.csv')
akc.isnull().sum()

Unnamed: 0                      0
description                     0
temperament                     1
popularity                     79
min_height                      0
max_height                      0
min_weight                      2
max_weight                      2
min_expectancy                  3
max_expectancy                  3
group                           0
grooming_frequency_value        7
grooming_frequency_category     7
shedding_value                 20
shedding_category              20
energy_level_value              6
energy_level_category           6
trainability_value             24
trainability_category          24
demeanor_value                 25
demeanor_category              25
dtype: int64

In [2]:
import pandas as pd
akc = pd.read_csv('data/raw/akc-dog-breeds.csv')
akc.shape

(277, 21)

In [3]:
import pandas as pd
akc = pd.read_csv('data/raw/akc-dog-breeds.csv')
akc.columns

Index(['Unnamed: 0', 'description', 'temperament', 'popularity', 'min_height',
       'max_height', 'min_weight', 'max_weight', 'min_expectancy',
       'max_expectancy', 'group', 'grooming_frequency_value',
       'grooming_frequency_category', 'shedding_value', 'shedding_category',
       'energy_level_value', 'energy_level_category', 'trainability_value',
       'trainability_category', 'demeanor_value', 'demeanor_category'],
      dtype='str')

In [4]:
import pandas as pd
akc = pd.read_csv('data/raw/akc-dog-breeds.csv')
akc.info()

<class 'pandas.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   277 non-null    str
 1   description                  277 non-null    str
 2   temperament                  276 non-null    str
 3   popularity                   198 non-null    str
 4   min_height                   277 non-null    float64
 5   max_height                   277 non-null    float64
 6   min_weight                   275 non-null    float64
 7   max_weight                   275 non-null    float64
 8   min_expectancy               274 non-null    float64
 9   max_expectancy               274 non-null    float64
 10  group                        277 non-null    str
 11  grooming_frequency_value     270 non-null    float64
 12  grooming_frequency_category  270 non-null    str
 13  shedding_value               257 non-null    float64
 14  shedding_category            257 non-null    str
 15  energy_level_value           271 non-null    float64
 16  energy_level_category        271 non-null    str
 17  trainability_value           253 non-null    float64
 18  trainability_category        253 non-null    str
 19  demeanor_value               252 non-null    float64
 20  demeanor_category            252 non-null    str
dtypes: float64(11), str(10)
memory usage: 334.1 KB

In [5]:
import pandas as pd
akc = pd.read_csv('data/raw/akc-dog-breeds.csv')
akc.describe()

,min_height,max_height,min_weight,max_weight,min_expectancy,max_expectancy,grooming_frequency_value,shedding_value,energy_level_value,trainability_value,demeanor_value
count,277.000000,277.000000,275.000000,275.000000,274.000000,274.000000,270.000000,257.000000,271.000000,253.000000,252.000000
mean,44.225801,52.720588,17.888858,27.291416,11.306569,13.832117,0.425926,0.529183,0.712915,0.624506,0.620635
std,14.238298,15.885454,12.290600,19.061416,1.817949,2.016668,0.198306,0.189068,0.168927,0.247271,0.201713
min,12.700000,17.780000,0.000000,0.000000,0.000000,0.000000,0.200000,0.200000,0.200000,0.200000,0.200000
25%,33.020000,38.100000,8.164663,12.927383,10.000000,13.000000,0.200000,0.400000,0.600000,0.400000,0.400000
50%,45.085000,53.340000,15.875733,24.947580,12.000000,14.000000,0.400000,0.600000,0.600000,0.600000,0.600000
75%,55.880000,66.040000,22.679619,34.019428,12.000000,15.000000,0.600000,0.600000,0.800000,0.800000,0.800000
max,76.200000,88.900000,68.038855,108.862169,16.000000,19.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
import pandas as pd
dogtime = pd.read_csv('data/raw/dogtime-dataset.csv')
dogtime.shape

(349, 37)

In [8]:
import pandas as pd
dogtime = pd.read_csv('data/raw/dogtime-dataset.csv')
dogtime.info()

<class 'pandas.DataFrame'>
RangeIndex: 349 entries, 0 to 348
Data columns (total 37 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   breed                               349 non-null    str
 1   url                                 349 non-null    str
 2   a_adaptability                      349 non-null    int64
 3   a1_adapts_well_to_apartment_living  349 non-null    int64
 4   a2_good_for_novice_owners           349 non-null    int64
 5   a3_sensitivity_level                349 non-null    int64
 6   a4_tolerates_being_alone            349 non-null    int64
 7   a5_tolerates_cold_weather           349 non-null    int64
 8   a6_tolerates_hot_weather            349 non-null    int64
 9   b_all_around_friendliness           349 non-null    int64
 10  b1_affectionate_with_family         349 non-null    int64
 11  b2_incredibly_kid_friendly_dogs     349 non-null    int64
 12  b3_dog_friendly                     349 non-null    int64
 13  b4_friendly_toward_strangers        349 non-null    int64
 14  c_health_grooming                   349 non-null    int64
 15  c1_amount_of_shedding               349 non-null    int64
 16  c2_drooling_potential               349 non-null    int64
 17  c3_easy_to_groom                    349 non-null    int64
 18  c4_general_health                   349 non-null    int64
 19  c5_potential_for_weight_gain        349 non-null    int64
 20  c6_size                             349 non-null    int64
 21  d_trainability                      349 non-null    int64
 22  d1_easy_to_train                    349 non-null    int64
 23  d2_intelligence                     349 non-null    int64
 24  d3_potential_for_mouthiness         349 non-null    int64
 25  d4_prey_drive                       349 non-null    int64
 26  d5_tendency_to_bark_or_howl         349 non-null    int64
 27  d6_wanderlust_potential             349 non-null    int64
 28  e_exercise_needs                    349 non-null    int64
 29  e1_energy_level                     349 non-null    int64
 30  e2_intensity                        349 non-null    int64
 31  e3_exercise_needs                   349 non-null    int64
 32  e4_potential_for_playfulness        349 non-null    int64
 33  breed_group                         349 non-null    str
 34  height                              348 non-null    str
 35  weight                              343 non-null    str
 36  life_span                           349 non-null    str
dtypes: int64(31), str(6)
memory usage: 146.9 KB

In [9]:
import pandas as pd
austin = pd.read_csv('data/raw/aac_intakes_outcomes.csv')
austin.shape

(79672, 41)

In [10]:
import pandas as pd
austin = pd.read_csv('data/raw/aac_intakes_outcomes.csv')
austin.info()

<class 'pandas.DataFrame'>
RangeIndex: 79672 entries, 0 to 79671
Data columns (total 41 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age_upon_outcome            79672 non-null  str
 1   animal_id_outcome           79672 non-null  str
 2   date_of_birth               79672 non-null  str
 3   outcome_subtype             36348 non-null  str
 4   outcome_type                79662 non-null  str
 5   sex_upon_outcome            79671 non-null  str
 6   age_upon_outcome_(days)     79672 non-null  int64
 7   age_upon_outcome_(years)    79672 non-null  float64
 8   age_upon_outcome_age_group  79672 non-null  str
 9   outcome_datetime            79672 non-null  str
 10  outcome_month               79672 non-null  int64
 11  outcome_year                79672 non-null  int64
 12  outcome_monthyear           79672 non-null  str
 13  outcome_weekday             79672 non-null  str
 14  outcome_hour                79672 non-null  int64
 15  outcome_number              79672 non-null  float64
 16  dob_year                    79672 non-null  int64
 17  dob_month                   79672 non-null  int64
 18  dob_monthyear               79672 non-null  str
 19  age_upon_intake             79672 non-null  str
 20  animal_id_intake            79672 non-null  str
 21  animal_type                 79672 non-null  str
 22  breed                       79672 non-null  str
 23  color                       79672 non-null  str
 24  found_location              79672 non-null  str
 25  intake_condition            79672 non-null  str
 26  intake_type                 79672 non-null  str
 27  sex_upon_intake             79671 non-null  str
 28  count                       79672 non-null  int64
 29  age_upon_intake_(days)      79672 non-null  int64
 30  age_upon_intake_(years)     79672 non-null  float64
 31  age_upon_intake_age_group   79672 non-null  str
 32  intake_datetime             79672 non-null  str
 33  intake_month                79672 non-null  int64
 34  intake_year                 79672 non-null  int64
 35  intake_monthyear            79672 non-null  str
 36  intake_weekday              79672 non-null  str
 37  intake_hour                 79672 non-null  int64
 38  intake_number               79672 non-null  float64
 39  time_in_shelter             79672 non-null  str
 40  time_in_shelter_days        79672 non-null  float64
dtypes: float64(5), int64(11), str(25)
memory usage: 46.4 MB

In [12]:
import pandas as pd
austin = pd.read_csv('data/raw/aac_intakes_outcomes.csv')
austin['animal_type'].value_counts()

animal_type
Dog      45366
Cat      29539
Other     4428
Bird       339
Name: count, dtype: int64

In [14]:
import pandas as pd
austin = pd.read_csv('data/raw/aac_intakes_outcomes.csv')
austin['breed'].value_counts()

breed
Domestic Shorthair Mix              23423
Pit Bull Mix                         6256
Chihuahua Shorthair Mix              4831
Labrador Retriever Mix               4789
Domestic Medium Hair Mix             2326
                                    ...
Golden Retriever/Border Terrier         1
Pomeranian/Beagle                       1
Yorkshire Terrier/Dachshund             1
Norfolk Terrier/Pug                     1
Australian Shepherd/Basset Hound        1
Name: count, Length: 2155, dtype: int64

In [21]:
import pandas as pd
austin = pd.read_csv('data/raw/aac_intakes_outcomes.csv')
dogs = austin[austin['animal_type'] == 'Dog']
dogs['breed'].value_counts().head(30)

breed
Pit Bull Mix                     6256
Chihuahua Shorthair Mix          4831
Labrador Retriever Mix           4789
German Shepherd Mix              1950
Australian Cattle Dog Mix        1099
Dachshund Mix                     811
Boxer Mix                         683
Border Collie Mix                 662
Miniature Poodle Mix              662
Catahoula Mix                     480
Rat Terrier Mix                   469
Australian Shepherd Mix           468
Yorkshire Terrier Mix             447
Siberian Husky Mix                441
Jack Russell Terrier Mix          429
Miniature Schnauzer Mix           402
Beagle Mix                        392
Staffordshire Mix                 375
Chihuahua Longhair Mix            371
Great Pyrenees Mix                349
Cairn Terrier Mix                 348
Pointer Mix                       336
Rottweiler Mix                    325
American Bulldog Mix              318
Shih Tzu Mix                      292
Plott Hound Mix                   253
Anatol Shepherd Mix               253
Chihuahua Shorthair/Dachshund     251
Black Mouth Cur Mix               246
Australian Kelpie Mix             240
Name: count, dtype: int64

In [23]:
import pandas as pd
austin = pd.read_csv('data/raw/aac_intakes_outcomes.csv')
dogs = austin[austin['animal_type'] == 'Dog']
dogs['time_in_shelter_days'].describe()

count    45366.000000
mean        15.897242
std         44.430504
min          0.000000
25%          2.093229
50%          5.064583
75%         11.116667
max       1606.194444
Name: time_in_shelter_days, dtype: float64